#!/usr/bin/env python
"""
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
  This file is part of the Smart Developer Hub Project:
    http://www.smartdeveloperhub.org
  Center for Open Middleware
        http://www.centeropenmiddleware.com/
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
  Copyright (C) 2016 Center for Open Middleware.
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
            http://www.apache.org/licenses/LICENSE-2.0
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
"""

from datetime import datetime
from threading import Thread

from gitcollector import collector
from gitcollector import settings as config
from gitcollector import utils_amqp

__author__ = 'Alejandro F. Carrera'


def execute_collector():

    st = datetime.utcnow().strftime('%d %B %Y %H:%M:%S')
    config.print_message(' - %s (%s) executed at %s' % (config.GC_LONGNAME,
                                                        config.GC_VERSION,
                                                        st))

    if config.GC_USE_PASSWORD:
        config.print_message(' - Password: "%s"' % config.GC_PASSWORD)

    try:
        event_manager = utils_amqp.EventManager('http://%s:%s/api' %
                                                (config.GC_HOST,
                                                 config.GC_PORT),
                                                config.GC_AMQP_BROKER_HOST,
                                                config.GC_AMQP_BROKER_PORT,
                                                config.GC_AMQP_VIRTUAL_HOST,
                                                config.GC_AMQP_TIME)

        Thread(target=event_manager.start).start()

        __collector = collector.Collector(ip=config.GC_IP,
                                          port=config.GC_PORT,
                                          pwd=config.GC_PASSWORD,
                                          event_manager=event_manager)
        __collector.app.run(__collector.ip, __collector.port)

    except Exception as e:
        config.print_error(e.message)

    st = datetime.utcnow().strftime('%d %B %Y %H:%M:%S')
    config.print_message(' - %s (%s) finished at %s' % (config.GC_LONGNAME,
                                                        config.GC_VERSION,
                                                        st))


# MAIN
if __name__ == '__main__':
    execute_collector()
